### ISSUE TITLE
Incorrect Ionisation stage for Recombination/Continuum line emission (PRB)?

### ISSUE THREAD

**Issue by mattngc** [cherab/openadas#36]
After more thought I believe there is still a bug in the ionisation stage of a particular ADF11 rate, the PRB rate. We previously opened an issue on this (#20), where we changed the ionisation stage with respect to the ADAS ADF11 conventions.

The idea was that the rate should be accessed from the most intuitive charge state. So for ionisation and recombination processes, the rate for charge Z would mean ionisation from state Z to Z+1 and recombination from state Z to Z-1. Z is therefore always the current charge state with regards to the API request.

However, I now think this means the access pattern for line recombination/continuum power is incorrect. Copying what we previously agreed in https://github.com/cherab/openadas/issues/20#issuecomment-473305083:

4. plt - Line Emission from excitation

    line radiated power by charge n by electron impact excitation
    Z1 e [1, Zmax]
    radiation by state charge=Zmax (absolutely stripped ion) is impossible
    correction from adas to cherab: charge = Z1 -1

5. prb - Recombination and Bremsstrahlung

    radiated power by bremsstrahlung and and line rdiation due to recombination of charge n
    Z1 e [1, Zmax]
    radiation by recombination of charge 0 (neutral) is neglected (no negative ions)
    correction from adas to cherab: charge = Z1

I think the correction for 5. prb should read:
    correction from adas to cherab: charge = Z1 - 1

The logic for this is that if you request a rate for PLT or PRB you are requesting the radiation power for the current stage. If you request the PRB rate for charge = Z1 it should be the radiation power from state Z1 due to recombination from Z1 + 1. Therefore both PLT and PRB would be accessed from the same state.

Can @Mateasek, @jacklovell and @CnlPepper confirm that they agree with this logic?

Note this would not effect the existing code developed by @Mateasek in #16.

**Comment by Mateasek** [comment]
A basic atomic collision could be rewritten somehow as:

 \sum_n A_n -> sum_m A'_m

where A_n being a particle in a stage n before the collision and A'_m being the particle after the collision. I think that what should be unifying the api should be either passing the stage before the atomic process of after.  The approach we have chosen for the ionization/recombination processes is to pass the A_n stages (stages before the process). What you are proposing for the radiation tho is to use the A'_m stages (stages after the process), correct me if I'm mistaken.

 I think the only solution is to use the stage A_n before the process. At least from the point of view of ADAS structure. Usually these quantities are known and enter the balance equations. Moreover,  this is also what is unifying the PRB file (making its existence possible). It stores rates which are for 2 processes out of which one changes the charge of an ion (radiation due to recombination or sometimes nicely called free-bound radiation) and one does not (radiation due to bremsstrahlung or free-free radiation).

Z1 in prb files starts with number 1. If you would apply conversion +1 it would mean in cherab we would be starting at ion charge +2, so any radiation due to free-free and free-bound collisions with electrons and ions with +1 would be missing, wouldn't it?

Could you specify where exactly you see the discrepancy? I could try to look at where does it come from.

This is at least how I get the ADAS structure. Please correct me if my reasoning is wrong.

**Comment by Mateasek** [comment]
Sorry I misread the suggested correction, please ignore the respective paragraph...

**Comment by mattngc** [comment]
To articulate the question a bit more, its really about what you expect these interface functions to return.

```
def class AtomicData:

    def line_radiated_power_rate(self, ion, charge):
        pass

    def continuum_radiated_power_rate(self, ion, charge):
        pass
```
One of CHERAB's goals is to be as user friendly as possible. And also to be consistent in our API.

Here, `openadas.line_radiated_power_rate(ion, charge)` returns the total line radiation for (ion, charge). It returns a missing rates error if you call it for the fully ionised species, which makes sense considering a fully ionised species can't radiate any power.

Based on this experience, I would expect `openadas.continuum_radiated_power_rate(ion, charge)` to return the total continuum power of _this_ (ion, charge) state. Currently it returns the continuum power for the state below the current state, i,e, (ion, charge-1). For me this is a discrepancy in the API that breaks user expectations. But maybe its just me.

**Comment by jacklovell** [comment]
From my perspective, both approaches are valid. What's really key is that whichever one is chosen is explicitly documented, which up to this point hasn't been the case. That said, I think there will be less confusion among users if the treatment is consistent with other processes in Cherab rather than having this particular case being a special case. It looks like what Matt's proposing is more consistent with the rest of the code, so I'd be inclined to stick with that in this instance too.

**Comment by mattngc** [comment]
I've spoken with @CnlPepper and he agrees with @Mateasek, he thinks it should be relative to the starting state. Given we all seem to have different opinions on this I think the safest thing is to keep the current API and see if the issue comes up again.
