### ISSUE TITLE
Incorrect units for ADF11 PLT, PRB and PRC rates

### ISSUE THREAD

**Issue by mattngc** [cherab/openadas#37]
The radiation ADF11 rates are in different units to the others, they are in [W cm**3]. This means one of the density conversions is missing.

**Comment by Mateasek** [comment]
This should be fixed in PR #4. All the install methods for ADF11 file types in [install.py](https://github.com/Mateasek/cherab_openadas/blob/feature/frac_abundance/cherab/openadas/install.py) should be calling the [_notation_adf11_adas2cherab](https://github.com/Mateasek/cherab_openadas/blob/b98819213a17f2f0de6bcdc0a3c409aa74f2e2fb/cherab/openadas/install.py#L366) function which is taking care of the charge notation and units conversion.

**Comment by mattngc** [comment]
I think this is not quite true. The power rates get multiplied by two densities. Power in [W m^-3] = rate * ne * n_imp. So therefore the units of the rate must be [W cm**3] and the unit correction on line 390 would need to be applied twice. So something like

```
if filetype in ["plt", "prb", "prc"]:
    rate_cherab[i][j + charge_correction]["rates"] = Cm3ToM3.to(Cm3ToM3.to(10 ** rate_adas[i][j]["rates"]))
else:
    rate_cherab[i][j + charge_correction]["rates"] = Cm3ToM3.to(10 ** rate_adas[i][j]["rates"])
```

**Comment by mattngc** [comment]
I'm currently doing a benchmark against some ADAS examples and it definitely appears like there is a unit mismatch for PLT, PRB and PRC.

**Comment by mattngc** [comment]
Ok, I think you had it right the first time @Mateasek. I've just managed to get myself totally confused with the units. I've been working through this with @CnlPepper and I think we've located the bug I've been experiencing somewhere else. The above commit can be ignored.
